### ISSUE TITLE
issues regarding sac model .py and sac.train.py

### ISSUE THREAD

**Issue by Krishnendu1984** [BolunDai0216/DeepReinforcementLearning#2]
Dear Bolun Kindly tell me how to start with sac.model.py 
I want to know the basic algorithm of sac like how the algorithm works
first you have created critic model
then actor model

**Comment by BolunDai0216** [comment]
I think [Spinning Up](https://spinningup.openai.com/en/latest/algorithms/sac.html) gives a nice introduction to SAC, please take a look at it.

**Comment by Krishnendu1984** [comment]
Please explain the significance of action taken in 3 steps .How it is enhancing the performance

**Comment by Krishnendu1984** [comment]
for _ in range(action_repeat):
		obs_, reward_, done_, info_ = env.step(action)
		if done_ and reward_ == -100:
			reward_ = 0
		r = r + reward_
		if done_ and action_repeat != 1:
			return obs_, 0.0, done_, info_
		if action_repeat == 1:
			return obs_, r, done_, info_
		print(action_repeat)	
	return obs_,reward_scale * r, done_, info_

**Comment by Krishnendu1984** [comment]
Can you write some detail comments below each section or class in model.py and train.py codes to understand whats going on in each steps or lines of code.
I am unable to understand from spinning up

**Comment by BolunDai0216** [comment]
> ```python
> for _ in range(action_repeat):
> 	obs_, reward_, done_, info_ = env.step(action)
> 	if done_ and reward_ == -100:
> 		reward_ = 0
> 	r = r + reward_
> 	if done_ and action_repeat != 1:
> 		return obs_, 0.0, done_, info_
> 	if action_repeat == 1:
> 		return obs_, r, done_, info_
> 	print(action_repeat)	
> return obs_,reward_scale * r, done_, info_
> ```

In this code I did two things (inspired by [CreateAMind](https://mp.weixin.qq.com/s/8vgLGcpsWkF89ma7T2twRA)):
- Repeat the action `action_repeat` times: this helps with exploration because the generated motion is less jerky:
```python
for _ in range(action_repeat):
    ...
```
- If the env is terminated it will return a reward of -100, which is not good for the training, I replaced it with zero:
```python
if done_ and reward_ == -100:
	reward_ = 0

r = r + reward_

if done_ and action_repeat != 1:
	return obs_, 0.0, done_, info_
```

I strongly suggest that you read the original blog post by [CreateAMind](https://mp.weixin.qq.com/s/8vgLGcpsWkF89ma7T2twRA), you can translate it to English using Chrome.

Hope this helps.
